import Head from 'next/head'

import axios from 'axios'

import Quiz from '@Components/Quiz'

import QuizModel from "@Models/quiz"

import { Quiz as QuizType } from '@Types/quiz'
import { QuizProvider } from '@Components/Quiz/context'



export default function QuizPage({ data }) {
    return (<>
        <Head>
            <title>Quiz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <QuizProvider data={data}>
            <Quiz />
        </QuizProvider> */}

        <h1>{data.title}</h1>
        <p>{data.description}</p>
        <p>{data._id}</p>
    </>)
}



export async function getStaticPaths() {
    const quizzes = await QuizModel.find({}, ['_id']);
    
    const paths = quizzes.map( ({ _id }) => {
        return {
            params: { _id: _id.toString() }
        }
    })

    return {
        paths, 
        fallback: false
    }
}

export async function getStaticProps({ params }) {
    const { _id } = params

    const { data } = await axios.get( `http://localhost:3000/api/quiz/${_id}` );

    return {
        props: { data }
    }
}
