import Head from 'next/head'
import Link from 'next/link'

import axios from 'axios'

import { Quiz as QuizType } from '@Types/quiz'



interface Props {
    quizzes: QuizType
}



export default function Home({ data }: Props) {
    return (<>
        <Head>
            <title>Quiz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
            {data.map( ({ _id, title }) => (
                <Link href={`/quiz/${_id.toString()}`}>
                    {title}
                </Link>
            ))}
        </div>
    </>)
}




export async function getStaticProps() {
    const { data } = await axios.get( 'http://localhost:3000/api/quiz');

    return {
        props: {
            data
        }
    }
}
