import Head from 'next/head'

import Quiz from '@Components/Quiz'
import { Quiz as QuizType } from '@Types/quiz'
import { QuizProvider } from '@Components/Quiz/context'



interface Props {
    data: QuizType
}



export default function Home({ data }: Props) {
    return (<>
        <Head>
            <title>Quiz</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <QuizProvider data={data}>
            <Quiz />
        </QuizProvider>
    </>)
}



import data from '../data.json'

export async function getStaticProps() {
    return {
        props: {
            data
        }
    }
}
